services:
  db:
    container_name: wongames-db
    image: mongo:7.0
    restart: always
    ports:
      - ${DATABASE_PORT}:27017
    volumes:
      - ./mongodb:/data/db

  wongames-backend:
    container_name: wongames-backend
    build:
      context: ./wongames-backend
      dockerfile: Dockerfile.dev
    # Test something like this
    # command: "npm run start:dev"
    ports:
      - ${BACKEND_PORT}:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./wongames-backend:/app
      - /app/node_modules
    depends_on:
      - db
