name: wongames

services:
  wongames-db:
    container_name: wongames-db
    image: mongo:7.0
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    command: ["--port", "${DATABASE_PORT}"]
    volumes:
      - ./mongodb:/data/db

  db-admin:
    container_name: wongames-db-admin
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_PORT=${DATABASE_PORT}
      - ME_CONFIG_MONGODB_SERVER=wongames-db
    depends_on:
      - wongames-db


  wongames-backend:
    container_name: wongames-backend
    build:
      context: ./wongames-backend
      dockerfile: Dockerfile.dev
    ports:
      - ${BACKEND_PORT}:3000
    # Use this instead of environment
    # env_file:
    #   - ./.env.backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLOUDINARY_FOLDER=${CLOUDINARY_FOLDER}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    volumes:
      - ./wongames-backend:/app
      - ./wongames-backend/node_modules:/app/node_modules
    depends_on:
      - wongames-db
