services:
  wongames-backend:
    container_name: wongames-backend
    build:
      context: ./wongames-backend
      dockerfile: Dockerfile.dev
    ports:
      - 7100:7100
    volumes:
      - ./wongames-backend:/app
      - /app/node_modules