name: wongames

services:
  wongames-db:
    container_name: ${MONGODB_SERVER_NAME}
    image: mongo:7.0
    restart: always
    # TODO: Add auth
    command: ['--port', '${DATABASE_PORT}']
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./mongodb:/data/db

  db-admin:
    container_name: wongames-db-admin
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGODB_SERVER_NAME}:${DATABASE_PORT}
    depends_on:
      - wongames-db

  wongames-backend:
    container_name: wongames-backend
    build:
      context: ./wongames-backend
      dockerfile: Dockerfile.dev
    ports:
      - ${BACKEND_PORT}:3000
    # Use this instead of environment
    # env_file:
    #   - ./.env.backend
    environment:
      - DATABASE_URL=mongodb://${MONGODB_SERVER_NAME}:${DATABASE_PORT}/${DATABASE_NAME}
      - CLOUDINARY_FOLDER=${CLOUDINARY_FOLDER}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    volumes:
      - ./wongames-backend:/app
      - ./wongames-backend/node_modules:/app/node_modules
    depends_on:
      - wongames-db

  wongames-next:
    container_name: wongames-next
    build:
      context: ./wongames-next
      dockerfile: Dockerfile.dev
    ports:
      - ${NEXT_CLIENT_PORT}:3000
    volumes:
      - ./wongames-next:/app
      - ./wongames-next/node_modules:/app/node_modules
    depends_on:
      - wongames-backend
  
  wongames-nuxt:
    container_name: wongames-nuxt
    build:
      context: ./wongames-nuxt
      dockerfile: Dockerfile.dev
    ports:
      - ${NUXT_CLIENT_PORT}:3000
    volumes:
      - ./wongames-nuxt:/app
      - ./wongames-nuxt/node_modules:/app/node_modules
    depends_on:
      - wongames-backend

  wongames-qwik:
    container_name: wongames-qwik
    build:
      context: ./wongames-qwik
      dockerfile: Dockerfile.dev
    ports:
      - ${QWIK_CLIENT_PORT}:5173
    volumes:
      - ./wongames-qwik:/app
      - ./wongames-qwik/node_modules:/app/node_modules
    depends_on:
      - wongames-backend
