services:
  db:
    container_name: wongames-db
    image: mongo:7.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db

  wongames-backend:
    container_name: wongames-backend
    build:
      context: ./wongames-backend
      dockerfile: Dockerfile.dev
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ./wongames-backend:/app
      - /app/node_modules
    depends_on:
      - db
